services:
  - type: web
    name: military-app-backend
    env: node
    buildCommand: cd backend && bun install && bun run build
    startCommand: cd backend && bun run start
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: DATABASE_PATH
        value: "./data/database.sqlite"
    
  - type: web
    name: military-app-frontend
    env: static
    buildCommand: bun install && bun run build:web
    staticPublishPath: ./dist
    plan: free
    region: oregon
    envVars:
      - key: EXPO_PUBLIC_API_URL
        fromService:
          type: web
          name: military-app-backend
          property: host