services:
  - type: web
    name: military-app-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: DATABASE_URL
        value: "sqlite:///app/data/database.sqlite"
      - key: USE_SQLITE
        value: "true"
    
  - type: web
    name: military-app-frontend
    env: static
    buildCommand: bun install && bun run build:web
    staticPublishPath: ./dist
    plan: free
    region: oregon
    envVars:
      - key: EXPO_PUBLIC_API_URL
        fromService:
          type: web
          name: military-app-backend
          property: host